// This file is normally regenerated by `payload generate:importmap` after
// adding/removing a custom admin component. That command is currently
// broken in this environment (ERR_REQUIRE_ASYNC_MODULE — the same tsx/ESM
// top-level-await interop bug documented for `payload migrate:create` in
// docs/T0-PRODUCTION-READINESS.md, R-10). Confirmed live: a custom
// component registered in a collection's `admin.components` but missing
// here silently fails to render (no error — Payload just logs
// "PayloadComponent not found in importMap" server-side and skips it).
// Until the CLI works, add new entries here by hand, following the
// existing pattern.
//
// This bites every `richText` field too, not just custom components: any
// collection with a `type: "richText"` field needs
// `@payloadcms/richtext-lexical/rsc`'s `RscEntryLexicalField`/
// `RscEntryLexicalCell`/`LexicalDiffComponent` registered here, or the
// field silently doesn't render in the admin edit view at all (found live
// while adding the configured editor features — BlogPosts.body,
// Campaigns.body/terms, and Pages' richText block were all affected, this
// likely predates that change). AND every individual lexical *feature*
// (Bold, HeadingFeature, FixedToolbarFeature, TextStateFeature, ...) is
// itself a `ClientFeature: '@payloadcms/richtext-lexical/client#XyzClient'`
// string reference, resolved through this SAME import map — missing one
// doesn't error, it just quietly drops that one feature (e.g. the whole
// toolbar not rendering, with zero console/server error). If a new feature
// is added to `payload.config.ts`'s `editor`, its `...FeatureClient` export
// from `@payloadcms/richtext-lexical/client` needs an entry here too.
import default_0 from "../../../components/AdminLogo";
import default_1 from "../../../components/AdminIcon";
import default_2 from "../../../components/LoginBrandPanel";
import default_3 from "../../../components/ReorderWidget";
import default_4 from "../../../components/HelpButton";
import default_5 from "../../../components/DashboardWidgets";
import default_6 from "../../../components/RoleAwarePublishButton";
import default_7 from "../../../components/SidebarLogo";
import default_10 from "../../../components/ForgotPasswordDisabled";
import default_11 from "../../../components/LoginHistoryField";
import default_12 from "../../../components/LocalePreferenceSync";
import default_13 from "../../../components/ContentManagementView";
import default_14 from "../../../components/ContentManagementNavLink";
import default_15 from "../../../components/SaveOrSubmitButton";
import default_16 from "../../../components/UserAvatarIcon";
import default_17 from "../../../components/CustomAccountView";
import default_18 from "../../../components/UsersExportButton";
import default_19 from "../../../components/AuditLogsExportButton";
import default_20 from "../../../components/MediaFilterTabs";
import default_21 from "../../../components/MediaUsageField";
import default_22 from "../../../components/RememberEmailCheckbox";
import default_23 from "../../../components/LockedAccountsView";
import default_24 from "../../../components/LockedAccountsNavLink";
import default_25 from "../../../components/LockedAccountsBanner";
import default_26 from "../../../components/CampaignsExportButton";
import default_27 from "../../../components/LiveOrderField";
import default_28 from "../../../components/CategoriesExportButton";
import default_29 from "../../../components/BlogPostsExportButton";
import default_30 from "../../../components/FooterOrderField";
import default_31 from "../../../components/FeesAndLimitsView";
import default_32 from "../../../components/FeesAndLimitsNavLink";
import default_33 from "../../../components/CustomDashboardView";
import { S3ClientUploadHandler as S3ClientUploadHandler_2 } from "@payloadcms/storage-s3/client";
import { CollectionCards as CollectionCards_1 } from "@payloadcms/next/rsc";
import { RscEntryLexicalField, RscEntryLexicalCell, LexicalDiffComponent } from "@payloadcms/richtext-lexical/rsc";
import {
  BoldFeatureClient,
  ItalicFeatureClient,
  UnderlineFeatureClient,
  StrikethroughFeatureClient,
  SubscriptFeatureClient,
  SuperscriptFeatureClient,
  InlineCodeFeatureClient,
  ParagraphFeatureClient,
  HeadingFeatureClient,
  AlignFeatureClient,
  IndentFeatureClient,
  UnorderedListFeatureClient,
  OrderedListFeatureClient,
  ChecklistFeatureClient,
  LinkFeatureClient,
  RelationshipFeatureClient,
  BlockquoteFeatureClient,
  UploadFeatureClient,
  HorizontalRuleFeatureClient,
  InlineToolbarFeatureClient,
  FixedToolbarFeatureClient,
  TableFeatureClient,
  TextStateFeatureClient,
  BlocksFeatureClient,
} from "@payloadcms/richtext-lexical/client";

export const importMap = {
  "/components/AdminLogo#default": default_0,
  "/components/AdminIcon#default": default_1,
  "/components/LoginBrandPanel#default": default_2,
  "/components/ReorderWidget#default": default_3,
  "/components/HelpButton#default": default_4,
  "/components/DashboardWidgets#default": default_5,
  "/components/RoleAwarePublishButton#default": default_6,
  "/components/SidebarLogo#default": default_7,
  "/components/ForgotPasswordDisabled#default": default_10,
  "/components/LoginHistoryField#default": default_11,
  "/components/LocalePreferenceSync#default": default_12,
  "/components/ContentManagementView#default": default_13,
  "/components/ContentManagementNavLink#default": default_14,
  "/components/SaveOrSubmitButton#default": default_15,
  "/components/UserAvatarIcon#default": default_16,
  "/components/CustomAccountView#default": default_17,
  "/components/UsersExportButton#default": default_18,
  "/components/AuditLogsExportButton#default": default_19,
  "/components/MediaFilterTabs#default": default_20,
  "/components/MediaUsageField#default": default_21,
  "/components/RememberEmailCheckbox#default": default_22,
  "/components/LockedAccountsView#default": default_23,
  "/components/LockedAccountsNavLink#default": default_24,
  "/components/LockedAccountsBanner#default": default_25,
  "/components/CampaignsExportButton#default": default_26,
  "/components/LiveOrderField#default": default_27,
  "/components/CategoriesExportButton#default": default_28,
  "/components/BlogPostsExportButton#default": default_29,
  "/components/FooterOrderField#default": default_30,
  "/components/FeesAndLimitsView#default": default_31,
  "/components/FeesAndLimitsNavLink#default": default_32,
  "/components/CustomDashboardView#default": default_33,
  "@payloadcms/storage-s3/client#S3ClientUploadHandler": S3ClientUploadHandler_2,
  "@payloadcms/next/rsc#CollectionCards": CollectionCards_1,
  "@payloadcms/richtext-lexical/rsc#RscEntryLexicalField": RscEntryLexicalField,
  "@payloadcms/richtext-lexical/rsc#RscEntryLexicalCell": RscEntryLexicalCell,
  "@payloadcms/richtext-lexical/rsc#LexicalDiffComponent": LexicalDiffComponent,
  "@payloadcms/richtext-lexical/client#BoldFeatureClient": BoldFeatureClient,
  "@payloadcms/richtext-lexical/client#ItalicFeatureClient": ItalicFeatureClient,
  "@payloadcms/richtext-lexical/client#UnderlineFeatureClient": UnderlineFeatureClient,
  "@payloadcms/richtext-lexical/client#StrikethroughFeatureClient": StrikethroughFeatureClient,
  "@payloadcms/richtext-lexical/client#SubscriptFeatureClient": SubscriptFeatureClient,
  "@payloadcms/richtext-lexical/client#SuperscriptFeatureClient": SuperscriptFeatureClient,
  "@payloadcms/richtext-lexical/client#InlineCodeFeatureClient": InlineCodeFeatureClient,
  "@payloadcms/richtext-lexical/client#ParagraphFeatureClient": ParagraphFeatureClient,
  "@payloadcms/richtext-lexical/client#HeadingFeatureClient": HeadingFeatureClient,
  "@payloadcms/richtext-lexical/client#AlignFeatureClient": AlignFeatureClient,
  "@payloadcms/richtext-lexical/client#IndentFeatureClient": IndentFeatureClient,
  "@payloadcms/richtext-lexical/client#UnorderedListFeatureClient": UnorderedListFeatureClient,
  "@payloadcms/richtext-lexical/client#OrderedListFeatureClient": OrderedListFeatureClient,
  "@payloadcms/richtext-lexical/client#ChecklistFeatureClient": ChecklistFeatureClient,
  "@payloadcms/richtext-lexical/client#LinkFeatureClient": LinkFeatureClient,
  "@payloadcms/richtext-lexical/client#RelationshipFeatureClient": RelationshipFeatureClient,
  "@payloadcms/richtext-lexical/client#BlockquoteFeatureClient": BlockquoteFeatureClient,
  "@payloadcms/richtext-lexical/client#UploadFeatureClient": UploadFeatureClient,
  "@payloadcms/richtext-lexical/client#HorizontalRuleFeatureClient": HorizontalRuleFeatureClient,
  "@payloadcms/richtext-lexical/client#InlineToolbarFeatureClient": InlineToolbarFeatureClient,
  "@payloadcms/richtext-lexical/client#FixedToolbarFeatureClient": FixedToolbarFeatureClient,
  "@payloadcms/richtext-lexical/client#TableFeatureClient": TableFeatureClient,
  "@payloadcms/richtext-lexical/client#TextStateFeatureClient": TextStateFeatureClient,
  "@payloadcms/richtext-lexical/client#BlocksFeatureClient": BlocksFeatureClient,
};
