// This file is normally regenerated by `payload generate:importmap` after
// adding/removing a custom admin component. That command is currently
// broken in this environment (ERR_REQUIRE_ASYNC_MODULE — the same tsx/ESM
// top-level-await interop bug documented for `payload migrate:create` in
// docs/T0-PRODUCTION-READINESS.md, R-10). Confirmed live: a custom
// component registered in a collection's `admin.components` but missing
// here silently fails to render (no error — Payload just logs
// "PayloadComponent not found in importMap" server-side and skips it).
// Until the CLI works, add new entries here by hand, following the
// existing pattern.
import default_0 from "../../../components/AdminLogo";
import default_1 from "../../../components/AdminIcon";
import default_2 from "../../../components/LoginBrandPanel";
import default_3 from "../../../components/ReorderWidget";
import default_4 from "../../../components/HelpButton";
import { S3ClientUploadHandler as S3ClientUploadHandler_2 } from "@payloadcms/storage-s3/client";

export const importMap = {
  "/components/AdminLogo#default": default_0,
  "/components/AdminIcon#default": default_1,
  "/components/LoginBrandPanel#default": default_2,
  "/components/ReorderWidget#default": default_3,
  "/components/HelpButton#default": default_4,
  "@payloadcms/storage-s3/client#S3ClientUploadHandler": S3ClientUploadHandler_2,
};
