// This file is normally regenerated by `payload generate:importmap` after
// adding/removing a custom admin component. That command is currently
// broken in this environment (ERR_REQUIRE_ASYNC_MODULE — the same tsx/ESM
// top-level-await interop bug documented for `payload migrate:create` in
// docs/T0-PRODUCTION-READINESS.md, R-10). Confirmed live: a custom
// component registered in a collection's `admin.components` but missing
// here silently fails to render (no error — Payload just logs
// "PayloadComponent not found in importMap" server-side and skips it).
// Until the CLI works, add new entries here by hand, following the
// existing pattern.
import default_0 from "../../../components/AdminLogo";
import default_1 from "../../../components/AdminIcon";
import default_2 from "../../../components/LoginBrandPanel";
import default_3 from "../../../components/ReorderWidget";
import default_4 from "../../../components/HelpButton";
import default_5 from "../../../components/DashboardWidgets";
import default_6 from "../../../components/RoleAwarePublishButton";
import default_7 from "../../../components/SidebarLogo";
import default_8 from "../../../components/WaitingApprovalsView";
import default_9 from "../../../components/WaitingApprovalsNavLink";
import default_10 from "../../../components/ForgotPasswordDisabled";
import default_11 from "../../../components/LoginHistoryField";
import default_12 from "../../../components/LocalePreferenceSync";
import default_13 from "../../../components/ContentManagementView";
import default_14 from "../../../components/ContentManagementNavLink";
import default_15 from "../../../components/SaveOrSubmitButton";
import default_16 from "../../../components/UserAvatarIcon";
import default_17 from "../../../components/CustomAccountView";
import default_18 from "../../../components/UsersExportButton";
import default_19 from "../../../components/AuditLogsExportButton";
import { S3ClientUploadHandler as S3ClientUploadHandler_2 } from "@payloadcms/storage-s3/client";
import { CollectionCards as CollectionCards_1 } from "@payloadcms/next/rsc";

export const importMap = {
  "/components/AdminLogo#default": default_0,
  "/components/AdminIcon#default": default_1,
  "/components/LoginBrandPanel#default": default_2,
  "/components/ReorderWidget#default": default_3,
  "/components/HelpButton#default": default_4,
  "/components/DashboardWidgets#default": default_5,
  "/components/RoleAwarePublishButton#default": default_6,
  "/components/SidebarLogo#default": default_7,
  "/components/WaitingApprovalsView#default": default_8,
  "/components/WaitingApprovalsNavLink#default": default_9,
  "/components/ForgotPasswordDisabled#default": default_10,
  "/components/LoginHistoryField#default": default_11,
  "/components/LocalePreferenceSync#default": default_12,
  "/components/ContentManagementView#default": default_13,
  "/components/ContentManagementNavLink#default": default_14,
  "/components/SaveOrSubmitButton#default": default_15,
  "/components/UserAvatarIcon#default": default_16,
  "/components/CustomAccountView#default": default_17,
  "/components/UsersExportButton#default": default_18,
  "/components/AuditLogsExportButton#default": default_19,
  "@payloadcms/storage-s3/client#S3ClientUploadHandler": S3ClientUploadHandler_2,
  "@payloadcms/next/rsc#CollectionCards": CollectionCards_1,
};
